<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \IiifFromFile\Form\IiifFromFileForm $form
 */

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');

$form->prepare();

$this->htmlElement('body')->appendAttribute('class', 'iiif-from-file');
?>

<?= $this->pageTitle($translate('IIIF from File')) ?>

<p>
    <?= $translate('Export local image files to a remote IIIF-compatible repository. The local files will be replaced by IIIF image references.') // @translate ?>
</p>

<?= $this->form()->openTag($form) ?>

<div id="page-actions">
    <?= $this->formElement($form->get('submit')) ?>
</div>

<?php

foreach ($form as $element):
    $name = $element->getName();
    if ($name === 'submit') continue;
    echo $this->formRow($element);
endforeach;
?>

<?= $this->form()->closeTag() ?>
